import { AidCase } from "./schema";

export const seedCases: AidCase[] = [
  {
    id: "case-001",
    applicantFullName: "Maria Lopez",
    dateOfBirth: "1990-08-11",
    householdSize: 3,
    address: "123 Cedar Ave Apt 4",
    city: "Riverton",
    state: "CA",
    zipCode: "92101",
    phone: "555-213-9088",
    email: "maria.demo@example.com",
    preferredContactMethod: "Phone",
    lifeEvent: "Job loss",
    monthlyIncome: 0,
    employmentStatus: "Unemployed",
    urgentNeeds: ["Food assistance", "Rent support"],
    documents: [
      { id: "doc-1", name: "Photo ID", status: "uploaded", url: "/docs/id.pdf" },
      { id: "doc-2", name: "Termination Letter", status: "uploaded", url: "/docs/termination.pdf" },
      { id: "doc-3", name: "Proof of Address", status: "uploaded", url: "/docs/address.pdf" },
    ],
    consentToSubmit: true,
  },
  {
    id: "case-002",
    applicantFullName: "Kevin Carter",
    dateOfBirth: "1986-02-19",
    householdSize: 2,
    address: "89 Willow Street",
    city: "Mesa Park",
    state: "CA",
    zipCode: "92103",
    phone: "555-884-1002",
    email: "kevin.demo@example.com",
    preferredContactMethod: "Email",
    lifeEvent: "Sudden illness",
    monthlyIncome: 1200,
    employmentStatus: "Unable to work",
    urgentNeeds: ["Medical assistance", "Utility support"],
    documents: [
      { id: "doc-1", name: "Photo ID", status: "uploaded", url: "/docs/id.pdf" },
      { id: "doc-2", name: "Doctor Note", status: "uploaded", url: "/docs/doctor.pdf" },
      { id: "doc-3", name: "Recent Pay Stub", status: "missing" },
    ],
    consentToSubmit: true,
  },
  {
    id: "case-003",
    applicantFullName: "Alina Brooks",
    dateOfBirth: "1994-05-26",
    householdSize: 4,
    address: "Temporary Shelter - Intake Desk",
    city: "Harbor City",
    state: "CA",
    zipCode: "92109",
    phone: "555-443-7812",
    email: "alina.demo@example.com",
    preferredContactMethod: "Text",
    lifeEvent: "Disaster displacement",
    monthlyIncome: 300,
    employmentStatus: "Displaced",
    urgentNeeds: ["Emergency shelter", "Food assistance"],
    documents: [
      { id: "doc-1", name: "Photo ID", status: "missing" },
      { id: "doc-2", name: "Displacement Verification", status: "uploaded", url: "/docs/disaster.pdf" },
    ],
    consentToSubmit: true,
  },
];